// ABOUT: Unit tests for the opener-shape classifier and corpus-uniformity assertion
// ABOUT: Asserts that the committed trial corpus stays varied (TD-031 regression guard)

import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import {
  classifyOpenerShape,
  distributionByShape,
  maxShareByShape,
  type OpenerShape,
} from './openerShape'

describe('classifyOpenerShape', () => {
  it('catches mistaken-identity templates', () => {
    expect(classifyOpenerShape('What I had first taken for a fragment of coral...')).toBe('mistaken-identity')
    expect(classifyOpenerShape('What I took at first for a stone...')).toBe('mistaken-identity')
  })

  it('catches rhetorical-question templates', () => {
    expect(classifyOpenerShape('By what curious accident does this creature persist?')).toBe('rhetorical-question')
    expect(classifyOpenerShape('By what singular geometry...')).toBe('rhetorical-question')
  })

  it('catches temporal-prepositional openers', () => {
    expect(classifyOpenerShape('Upon dredging the abyssal floor...')).toBe('temporal-prepositional')
    expect(classifyOpenerShape('When I first observed the specimen...')).toBe('temporal-prepositional')
    expect(classifyOpenerShape('Whilst surveying the shore...')).toBe('temporal-prepositional')
    expect(classifyOpenerShape('At first the form seemed...')).toBe('temporal-prepositional')
    expect(classifyOpenerShape('While dredging the sediments...')).toBe('temporal-prepositional')
  })

  it('catches generic specimen-introduction openers', () => {
    expect(classifyOpenerShape('The creature presents an unusual form.')).toBe('generic-introduction')
    expect(classifyOpenerShape('This specimen exhibits remarkable symmetry.')).toBe('generic-introduction')
  })

  it('catches body-part-first openers including abstract-property leads', () => {
    expect(classifyOpenerShape('The eyes caught the lantern light.')).toBe('body-part-first')
    expect(classifyOpenerShape('The crown of fronds rose...')).toBe('body-part-first')
    expect(classifyOpenerShape('The radial symmetry struck me first.')).toBe('body-part-first')
    expect(classifyOpenerShape('The form of the specimen...')).toBe('body-part-first')
    expect(classifyOpenerShape('The colouration caught my eye.')).toBe('body-part-first')
    expect(classifyOpenerShape('The delicate filaments trailed in the current.')).toBe('body-part-first')
  })

  it('catches setting-first openers', () => {
    expect(classifyOpenerShape('Among the kelp fronds...')).toBe('setting-first')
    expect(classifyOpenerShape('In the abyssal sediments of the deep trench...')).toBe('setting-first')
    expect(classifyOpenerShape('Beneath the surface...')).toBe('setting-first')
  })

  it('catches numeric-feature openers', () => {
    expect(classifyOpenerShape('Three eyes regarded me...')).toBe('numeric-feature')
    expect(classifyOpenerShape('Six tentacles unfurled...')).toBe('numeric-feature')
  })

  it('returns "other" for novel openers', () => {
    expect(classifyOpenerShape('I discovered this specimen by accident.')).toBe('other')
    expect(classifyOpenerShape('A curious glimmer caught my eye.')).toBe('other')
  })
})

describe('distributionByShape', () => {
  it('counts each shape', () => {
    const counts = distributionByShape([
      'Upon arriving at the shore...',
      'When I first saw...',
      'The creature presents...',
      'I discovered...',
    ])
    expect(counts['temporal-prepositional']).toBe(2)
    expect(counts['generic-introduction']).toBe(1)
    expect(counts.other).toBe(1)
  })
})

describe('maxShareByShape', () => {
  it('returns the dominant shape and its share', () => {
    const result = maxShareByShape(['Upon arriving...', 'When I came...', 'The creature presents...'])
    expect(result.shape).toBe('temporal-prepositional')
    expect(result.share).toBeCloseTo(2 / 3)
  })

  it('returns 0 for empty input', () => {
    expect(maxShareByShape([])).toEqual({ shape: 'other', share: 0 })
  })
})

// ── TD-031 corpus regression test ───────────────────────────────────────────
// Asserts that the committed trial corpus, generated by `scripts/trial-field-notes.ts`,
// stays varied. If the prompt drifts back toward uniformity, this fails — forcing a
// regenerate-and-revalidate before the change can land.

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const repoRoot = join(__dirname, '..', '..')
const TRIAL_PATH = join(repoRoot, 'scripts/output/trial-field-notes.json')

interface TrialSample {
  qr_hash: string
  first_sentence: string
}

interface TrialOutput {
  sample_count: number
  samples: TrialSample[]
}

describe('TD-031 corpus uniformity guard', () => {
  if (!existsSync(TRIAL_PATH)) {
    it.skip('trial-field-notes.json missing — run `npx tsx scripts/trial-field-notes.ts`', () => {})
    return
  }

  const trial = JSON.parse(readFileSync(TRIAL_PATH, 'utf-8')) as TrialOutput
  const sentences = trial.samples.map((s) => s.first_sentence)

  it('has at least 10 samples to be statistically meaningful', () => {
    expect(sentences.length).toBeGreaterThanOrEqual(10)
  })

  it('keeps every templated opener-shape under 35% of the corpus', () => {
    // Under 6-way directive rotation, expected per-shape share is ~16–25% with
    // sampling noise at n=16. A 35% cap is roughly 2x expected — loose enough
    // for noise, tight enough to fail noisily on real drift (the original
    // TD-031 disease was 67% "Upon...", so this catches it with massive
    // headroom).
    const counts = distributionByShape(sentences)
    const total = sentences.length
    const templated: OpenerShape[] = [
      'temporal-prepositional',
      'generic-introduction',
      'body-part-first',
      'numeric-feature',
      'setting-first',
      'mistaken-identity',
      'rhetorical-question',
    ]
    for (const shape of templated) {
      const share = counts[shape] / total
      expect(
        share,
        `${shape} = ${counts[shape]}/${total} = ${(share * 100).toFixed(0)}% (limit 35%)`,
      ).toBeLessThanOrEqual(0.35)
    }
  })

  it('uses at least 4 distinct opener shapes across the corpus', () => {
    // Under the seed-rotated directive design, samples legitimately land in
    // templated buckets (4 of 6 directives map to templated shapes). The guard
    // against uniformity is shape diversity, not an "other" floor.
    const counts = distributionByShape(sentences)
    const shapesUsed = Object.values(counts).filter((n) => n > 0).length
    expect(shapesUsed).toBeGreaterThanOrEqual(4)
  })

  it('keeps the most-common first word under 35% of the corpus', () => {
    const firstWords = sentences.map((s) => s.trim().split(/[\s,.]/)[0].toLowerCase())
    const counts: Record<string, number> = {}
    for (const w of firstWords) counts[w] = (counts[w] ?? 0) + 1
    const top = Math.max(...Object.values(counts))
    expect(top / firstWords.length).toBeLessThanOrEqual(0.35)
  })
})
